#!/bin/bash

#Timestamp checks
INDIR="/media/flash/nfs/datadir0"
INFILE="$INDIR/$1"

TODAY=$(date "+%Y%m%d")
LMODTIME=$(date -r $INFILE "+%H%M")
LMODDATE=$(date -r $INFILE "+%Y%m%d")

# Directory and file naming

OUTDIRROOT="/media/flash/archive"
DIRNAME=$LMODDATE
FNAME=$(echo $1 | sed "s/\..*//")
OUTDIR="$OUTDIRROOT/$DIRNAME/$FNAME"

mkdir $OUTDIR
SEEK=0

LENGTH=$(get-length $1)  #vid length in secs
REPS=$(echo "($LENGTH / 300)" | bc) #integer division w/ 300s

for ((N = 0; N <= $REPS; N++));
do
	OUTFILE="$OUTDIR/$N.mp4"
	echo "Converting $N to $OUTDIR/$OUTFILE" >> batch-here.txt
	ffmpeg -hide_banner -loglevel warning -n -i $1 -ss $SEEK -t 300 -c:v hevc_nvmpi -b:v 250k -vf scale=-1:360 $OUTFILE
	SEEK=$((SEEK+300))
done
