#!/bin/bash

function conv()
{
  ffmpeg -hide_banner -n -i $1 -ss $2 -t 300 -c:v hevc_nvmpi -b:v 250k -vf scale=w=iw/3:h=ih/3 $3
}

#Timestamp checks
INDIR="/media/flash/nfs/datadir0"
INFILE="$INDIR/$1"

TODAY=$(date "+%Y%m%d")
LMODTIME=$(date -r $INFILE "+%H%M")
LMODDATE=$(date -r $INFILE "+%Y%m%d")

# Directory and file naming

OUTDIRROOT="/media/flash/archive"
DIRNAME=$LMODDATE
FNAME=$(echo $1 | sed "s/\..*//")
OUTDIR="$OUTDIRROOT/$DIRNAME/$FNAME"

mkdir $OUTDIRROOT/$DIRNAME
mkdir $OUTDIR
SEEK=0

LENGTH=$(get-length $1)  #vid length in secs
REPS=$(echo "($LENGTH / 300)" | bc) #integer division w/ 300s

for ((N=0; N<=$REPS; N++))
do
	OUTFILE="$OUTDIR/$N.mp4"
  echo "Converting $1 to $OUTFILE at seektime $SEEK"
	echo "Converting $1 to $OUTFILE at seektime $SEEK" >> $OUTDIR/DEBUG.txt

	conv $1 $SEEK $OUTFILE

	SEEK=$((SEEK+300))
done
