#!/bin/bash

# SYNOPSIS:
# - The script takes no argument and is run manually from specific date dir
# - This script produces the mark4convert.txt containing path to split videos
#
# ASSUMPTIONS:
# - This script assumes the source videos are deleted after conversion
# - Duplicate is possible but non-breaking as the videos are assumed deleted

read -p "Are you sure this is the DATE directory? [y/N]: " yn
case $yn in
    [Yy]* )
			find $PWD/*/FULLRES -type f -name '*.mp4' >> /media/flash/archive/mark4convert.txt;;
    [Nn]* )
			exit;;
esac
