#!/bin/bash

echo "Reboot script called on $(date)" >> /media/flash/archive/auto-reboot.txt

# Flush disk writes
sync

# Making sure every NFS operation has REALLY stopped0
sleep 30
sudo service nfs stop

sudo reboot now

sleep 1
echo "This should never ever happen. Reboot failed!?" >> /var/log/auto-reboot.log
