#!/bin/bash

# SYNOPSIS:
# - The script takes no argument and is run from cron job every 4 minutes (TBD)
# - This script takes the first entry of mark4convert.txt in archive dir which
#   is the directory of newly split full-res footage:
#   $ARCHIVE/$DATE/$SOURCEFILE and outputs to $SOURCEFILE/output
# - The script should check for running ffmpeg and halts when true
# - Upon successful conversion it deletes source file and mark4convert.txt entry

# ASSUMPTIONS:
# - File splitting is done *MUCH* faster than conversion (TODO:Test)
# - File conversion can be deferred to splitting

TXTPATH="/media/flash/archive/mark4convert.txt"
LOGPATH="/media/flash/archive/timed-convert.txt"
INFILE=$(cat $TXTPATH | head -n 1)

# second level parent i.e. ../FULLRES/N.mp4
PARENT=$(dirname $INFILE)
PARENT=$(dirname $PARENT)

OUTFILE="$PARENT/$(basename -s ".mp4" $INFILE).mp4"

echo "Converting $INFILE to $OUTFILE" >> $LOGPATH
ffmpeg -hide_banner -loglevel error -i $INFILE -c:v hevc_nvmpi -b:v 250k -vf scale=w=iw/3:h=ih/3 $OUTFILE

#TODO: Check validity of the output file by making sure it's > 1M

#TODO: Delete source file after conversion

# Delete mark entry after conversion
awk 'NR > 1 { print }' < /media/flash/archive/mark4convert.txt
